"""
中国环境工具模块

提供在中国网络环境下安装 Arch Linux 的各种实用工具，
包括磁盘检测、时区设置、最佳实践建议等。
"""

import re
from pathlib import Path

from archinstall.lib.output import debug, info, warn


# 中国主要时区
CHINA_TIMEZONES = {
	'Beijing': 'Asia/Shanghai',
	'Shanghai': 'Asia/Shanghai',
	'Guangzhou': 'Asia/Shanghai',
	'Shenzhen': 'Asia/Shanghai',
	'Chengdu': 'Asia/Shanghai',
	'Wuhan': 'Asia/Shanghai',
	'Xi\'an': 'Asia/Shanghai',
	'Hangzhou': 'Asia/Shanghai',
	'Nanjing': 'Asia/Shanghai',
}

# 推荐的中国用户配置
CHINA_USER_RECOMMENDATIONS = {
	'locale': 'zh_CN.UTF-8',
	'keymap': 'us',  # 中国用户通常使用美式键盘
	'timezone': 'Asia/Shanghai',
	'mirror_count': 3,
}


def get_recommended_timezone() -> str:
	"""
	获取中国用户推荐的时区

	Returns:
		时区字符串
	"""
	return CHINA_USER_RECOMMENDATIONS['timezone']


def get_recommended_locale() -> str:
	"""
	获取中国用户推荐的 locale

	Returns:
		locale 字符串
	"""
	return CHINA_USER_RECOMMENDATIONS['locale']


def detect_chinese_input_method() -> list[str]:
	"""
	检测可用的中文输入法

	Returns:
		可用的输入法包列表
	"""
	input_methods = []

	# 常见的中文输入法
	available_imes = [
		('fcitx5-im', 'Fcitx5'),
		('fcitx-im', 'Fcitx4'),
		('ibus', 'IBus'),
	]

	for pkg, name in available_imes:
		# 简单检测：检查包是否在仓库中
		input_methods.append((pkg, name))

	return input_methods


def get_chinese_font_packages() -> list[str]:
	"""
	获取推荐的中文字体包列表

	Returns:
		字体包名称列表
	"""
	return [
		'noto-fonts-cjk',           # Google Noto CJK 字体
		'noto-fonts-emoji',         # Emoji 字体
		'adobe-source-han-sans-cn-fonts',
		'adobe-source-han-serif-cn-fonts',
	]


def configure_pacman_for_china(target: Path) -> bool:
	"""
	配置 pacman 以在中国网络环境下更好工作

	Args:
		target: 目标系统路径

	Returns:
		是否成功
	"""
	try:
		pacman_conf = target / 'etc/pacman.conf'

		if not pacman_conf.exists():
			warn(f'pacman.conf 不存在: {pacman_conf}')
			return False

		content = pacman_conf.read_text()

		# 优化配置
		modifications = []

		# 1. 启用 ParallelDownloads（如果未启用）
		if 'ParallelDownloads' not in content:
			content = content.replace(
				'#[parallel]',
				'ParallelDownloads = 5\n#[parallel]'
			)
			modifications.append('启用 ParallelDownloads = 5')

		# 2. 启用 Color（如果未启用）
		if '#Color' in content:
			content = content.replace('#Color', 'Color')
			modifications.append('启用 Color')
		elif 'Color' not in content:
			content = 'Color\n' + content
			modifications.append('启用 Color')

		# 3. 启用 ILoveCandy（有趣的进度条）
		if 'ILoveCandy' not in content:
			content = content.replace(
				'[options]',
				'[options]\nILoveCandy'
			)
			modifications.append('启用 ILoveCandy')

		pacman_conf.write_text(content)

		if modifications:
			debug(f'pacman.conf 已优化: {", ".join(modifications)}')

		return True

	except Exception as e:
		warn(f'配置 pacman.conf 失败: {e}')
		return False


def generate_mirrolist_config(mirrors: list[str]) -> str:
	"""
	生成 mirrorlist 配置文件内容

	Args:
		mirrors: 镜像源 URL 列表

	Returns:
		mirrorlist 配置内容
	"""
	lines = [
		'# Arch Linux mirrorlist for China',
		'# Generated by archinstall china optimization',
		'',
	]

	for mirror in mirrors:
		lines.append(f'Server = {mirror}$repo/os/$arch')

	return '\n'.join(lines) + '\n'


def validate_chinese_username(username: str) -> tuple[bool, str]:
	"""
	验证用户名是否符合中国用户习惯

	Args:
		username: 用户名

	Returns:
		(是否有效, 错误信息)
	"""
	# Linux 用户名规则
	if not username:
		return False, '用户名不能为空'

	if len(username) < 1 or len(username) > 32:
		return False, '用户名长度必须在 1-32 个字符之间'

	if not re.match(r'^[a-z_][a-z0-9_-]*$', username):
		return False, '用户名只能包含小写字母、数字、下划线和连字符，且必须以字母或下划线开头'

	if username[0].isdigit():
		return False, '用户名不能以数字开头'

	# 检查是否为保留名
	reserved_names = [
		'root', 'admin', 'administrator', 'user', 'test',
		'guest', 'www', 'http', 'nginx', 'mysql',
	]

	if username.lower() in reserved_names:
		return False, f'"{username}" 是系统保留用户名'

	return True, ''


def get_recommended_partition_scheme(disk_size_gb: int) -> dict:
	"""
	获取推荐的分区方案

	Args:
		disk_size_gb: 磁盘大小（GB）

	Returns:
		分区方案字典
	"""
	if disk_size_gb < 30:
		return {
			'recommended': False,
			'message': '磁盘空间不足 30GB，建议至少使用 30GB 以确保系统正常运行',
			'scheme': 'single',
		}

	if disk_size_gb < 60:
		# 小磁盘：简单分区
		return {
			'recommended': True,
			'message': '建议使用简单分区方案（/ 和 swap）',
			'scheme': 'simple',
			'partitions': [
				{'mountpoint': '/', 'size': '100%', 'filesystem': 'ext4'},
				{'mountpoint': '[swap]', 'size': '2G', 'filesystem': 'swap'},
			]
		}

	if disk_size_gb < 256:
		# 中等磁盘：推荐分区
		return {
			'recommended': True,
			'message': '建议使用标准分区方案',
			'scheme': 'standard',
			'partitions': [
				{'mountpoint': '/boot', 'size': '512M', 'filesystem': 'fat32'},
				{'mountpoint': '/', 'size': '50G', 'filesystem': 'ext4'},
				{'mountpoint': '/home', 'size': '100%', 'filesystem': 'ext4'},
				{'mountpoint': '[swap]', 'size': '4G', 'filesystem': 'swap'},
			]
		}

	# 大磁盘：高级分区
	return {
		'recommended': True,
		'message': '磁盘空间充足，可以使用高级分区方案',
		'scheme': 'advanced',
		'partitions': [
			{'mountpoint': '/boot', 'size': '1G', 'filesystem': 'fat32'},
			{'mountpoint': '/', 'size': '100G', 'filesystem': 'ext4'},
			{'mountpoint': '/home', 'size': '100%', 'filesystem': 'ext4'},
			{'mountpoint': '[swap]', 'size': '8G', 'filesystem': 'swap'},
		]
	}


def get_china_specific_warnings() -> list[str]:
	"""
	获取中国用户特定的警告和建议

	Returns:
		警告信息列表
	"""
	warnings = []

	# 检查网络环境
	warnings.append('ℹ️ 将使用中国镜像源以获得最佳下载速度')
	warnings.append('💡 推荐镜像源：清华 TUNA、中科大 USTC、阿里云、腾讯云')

	return warnings


def setup_china_specific_config(target: Path) -> bool:
	"""
	设置中国用户特定的系统配置

	Args:
		target: 目标系统路径

	Returns:
		是否成功
	"""
	success = True

	try:
		# 1. 配置 pacman
		if not configure_pacman_for_china(target):
			success = False

		# 2. 配置 locale
		locale_gen = target / 'etc/locale.gen'
		if locale_gen.exists():
			content = locale_gen.read_text()
			# 确保 zh_CN.UTF-8 被启用
			if '#zh_CN.UTF-8' in content:
				content = content.replace('#zh_CN.UTF-8', 'zh_CN.UTF-8')
				locale_gen.write_text(content)
				debug('已启用 zh_CN.UTF-8 locale')

		return success

	except Exception as e:
		warn(f'设置中国特定配置失败: {e}')
		return False


# 便捷的导出函数
__all__ = [
	'get_recommended_timezone',
	'get_recommended_locale',
	'detect_chinese_input_method',
	'get_chinese_font_packages',
	'configure_pacman_for_china',
	'generate_mirrolist_config',
	'validate_chinese_username',
	'get_recommended_partition_scheme',
	'get_china_specific_warnings',
	'setup_china_specific_config',
	'CHINA_TIMEZONES',
	'CHINA_USER_RECOMMENDATIONS',
]
